package app.michaelwoodroof.naughtsandcrosses.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Defines all the colours that the demo uses
 */
val primary = Color(0xFF8BC34A)
val onPrimary= Color(0xFFFFFFFF)
val primaryContainer= Color(0xFFFFFFFF)
val onPrimaryContainer= Color(0xFFFFFFFF)
val inversePrimary= Color(0xFFFFFFFF)
val secondary= Color(0xFFFFFFFF)
val onSecondary= Color(0xFFFFFFFF)
val secondaryContainer= Color(0xFFFFFFFF)
val onSecondaryContainer= Color(0xFFFFFFFF)
val tertiary= Color(0xFFFFFFFF)
val onTertiary= Color(0xFFFFFFFF)
val tertiaryContainer= Color(0xFFFFFFFF)
val onTertiaryContainer= Color(0xFFB4B8AB)
val background= Color(0xFFECEDE9)
val onBackground= Color(0xFF494949)
val surface= Color(0xFFFFFFFF)
val onSurface= Color(0xFF313131)
val surfaceVariant= Color(0xFFFFFFFF)
val onSurfaceVariant= Color(0xFFFFFFFF)
val surfaceTint = Color(0xFFFFFFFF)
val inverseSurface= Color(0xFFFFFFFF)
val inverseOnSurface= Color(0xFFFFFFFF)
val error= Color(0xFFF44336)
val onError= Color(0xFFFFFFFF)
val errorContainer= Color(0xFFFFFFFF)
val onErrorContainer= Color(0xFFFFFFFF)
val outline= Color(0xFFFFFFFF)

val primaryDark = Color(0xFF9BC06F)
val onPrimaryDark = Color(0xFFE0E0E0)
val primaryContainerDark = Color(0xFF292929)
val onPrimaryContainerDark = Color(0xFFE0E0E0)
val inversePrimaryDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFFFFF)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFFFFFFFF)
val onSecondaryContainerDark = Color(0xFFE0E0E0)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFFFFFFFF)
val onTertiaryContainerDark = Color(0xFFB4B8AB)
val backgroundDark = Color(0xFF252525)
val onBackgroundDark = Color(0xFFD1D1D1)
val surfaceDark = Color(0xFF333333)
val onSurfaceDark = Color(0xFFC9C9C9)
val surfaceVariantDark = Color(0xFF2C2C2C)
val onSurfaceVariantDark = Color(0xFFFFFFFF)
val surfaceTintDark = Color(0xFFFFFFFF)
val inverseSurfaceDark = Color(0xFFFFFFFF)
val inverseOnSurfaceDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFF18881)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFFFFFFFF)
val onErrorContainerDark = Color(0xFFFFFFFF)
val outlineDark = Color(0xFFFFFFFF)